// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetAuthApp.Data;

#nullable disable

namespace dotnetAuthApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230623102121_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("dotnetAuthApp.Models.DailyRepModel", b =>
                {
                    b.Property<int>("RepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Day")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repetitions")
                        .HasColumnType("INTEGER");

                    b.HasKey("RepId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("DailyRepSet");
                });

            modelBuilder.Entity("dotnetAuthApp.Models.ExerciseModel", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCommit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextCommit")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("ExerciseSet");
                });

            modelBuilder.Entity("dotnetAuthApp.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSet");
                });

            modelBuilder.Entity("dotnetAuthApp.Models.DailyRepModel", b =>
                {
                    b.HasOne("dotnetAuthApp.Models.ExerciseModel", "Exercise")
                        .WithMany("DailyReps")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("dotnetAuthApp.Models.ExerciseModel", b =>
                {
                    b.HasOne("dotnetAuthApp.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dotnetAuthApp.Models.ExerciseModel", b =>
                {
                    b.Navigation("DailyReps");
                });
#pragma warning restore 612, 618
        }
    }
}
